In [1]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.size)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements=> (6,)
dimension count 1


In [8]:
y = np.array([[2,3,5],[3,2,1]])
print(y)
print('total elements =>',y.size)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [3 2 1]]
total elements => 6
dimension wise elements=> (2, 3)
dimension count 2


In [9]:
z = np.array([[2,3,5],[3,2,1],[7,8,9]])
print(z)
print('total elements =>',z.size)
print('dimension wise elements=>',z.shape)
print('dimension count',z.ndim)

[[2 3 5]
 [3 2 1]
 [7 8 9]]
total elements => 9
dimension wise elements=> (3, 3)
dimension count 2


In [11]:
x= [1,2,3,4,5]
z= np.array([[x,x,x],[x,x,x],[x,x,x,]])
print('shape', z.shape)
print(z)

shape (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [14]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [16]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [18]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [21]:
a = np.linspace(1,1000,11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [26]:
d = np.random.randint(1,5,(10,10))


In [25]:
print(d)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5]


In [27]:
d[0][0]

1

In [28]:
d[-1]

array([2, 2, 2, 1, 4, 1, 1, 4, 2, 3])

In [29]:
d[3,5]

2

In [32]:
d[:,0] # all rows

array([1, 1, 2, 2, 3, 2, 2, 3, 3, 2])

In [33]:
d[:,-3]

array([3, 4, 1, 2, 2, 4, 2, 3, 4, 4])

In [ ]:
d[:5,2] #first five rows

In [36]:
d[:5 ,:5] 

array([[1, 2, 2, 2, 1],
       [1, 1, 4, 4, 3],
       [2, 4, 1, 2, 1],
       [2, 3, 2, 4, 4],
       [3, 3, 3, 3, 1]])

In [37]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x,'\n',y)

[[8 6 4]
 [9 4 9]
 [7 4 5]] 
 [[3 8 4]
 [3 6 9]
 [2 9 3]]


In [38]:
x + y

array([[11, 14,  8],
       [12, 10, 18],
       [ 9, 13,  8]])

In [39]:
x - y

array([[ 5, -2,  0],
       [ 6, -2,  0],
       [ 5, -5,  2]])

In [40]:
x * y

array([[24, 48, 16],
       [27, 24, 81],
       [14, 36, 15]])

In [41]:
x / y

array([[2.66666667, 0.75      , 1.        ],
       [3.        , 0.66666667, 1.        ],
       [3.5       , 0.44444444, 1.66666667]])

In [42]:
np.dot(x,y)

array([[ 50, 136,  98],
       [ 57, 177,  99],
       [ 43, 125,  79]])

In [43]:
np.matmul(x,y)

array([[ 50, 136,  98],
       [ 57, 177,  99],
       [ 43, 125,  79]])

In [44]:
np.multiply(x,y)

array([[24, 48, 16],
       [27, 24, 81],
       [14, 36, 15]])

In [45]:
np.cross(x,y)

array([[ -8, -20,  46],
       [-18, -54,  42],
       [-33, -11,  55]])

In [46]:
np.hstack([x,y])

array([[8, 6, 4, 3, 8, 4],
       [9, 4, 9, 3, 6, 9],
       [7, 4, 5, 2, 9, 3]])

In [47]:
np.vstack([x,y])

array([[8, 6, 4],
       [9, 4, 9],
       [7, 4, 5],
       [3, 8, 4],
       [3, 6, 9],
       [2, 9, 3]])

In [49]:
np.append(x,y,axis=0)

array([[8, 6, 4],
       [9, 4, 9],
       [7, 4, 5],
       [3, 8, 4],
       [3, 6, 9],
       [2, 9, 3]])

In [50]:
x.max()

9

In [52]:
x.max(axis=0)

array([9, 6, 9])

In [54]:
x.min(axis=1)

array([4, 4, 4])

In [55]:
x .flatten()

array([8, 6, 4, 9, 4, 9, 7, 4, 5])

In [58]:
d[d>3] #boolean filter

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4])

In [59]:
d[d==1] #give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])