In [1]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.size)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements=> (6,)
dimension count 1


In [8]:
y = np.array([[2,3,5],[3,2,1]])
print(y)
print('total elements =>',y.size)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [3 2 1]]
total elements => 6
dimension wise elements=> (2, 3)
dimension count 2


In [9]:
z = np.array([[2,3,5],[3,2,1],[7,8,9]])
print(z)
print('total elements =>',z.size)
print('dimension wise elements=>',z.shape)
print('dimension count',z.ndim)

[[2 3 5]
 [3 2 1]
 [7 8 9]]
total elements => 9
dimension wise elements=> (3, 3)
dimension count 2


In [11]:
x= [1,2,3,4,5]
z= np.array([[x,x,x],[x,x,x],[x,x,x,]])
print('shape', z.shape)
print(z)

shape (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
